# exampleSite/config.yaml
baseURL: https://blog.kierangroo.me/ # Replace with your domain
languageCode: en-gb
theme: smigle
themesDir: ../.. # Only needed for running the example site
title: blog.kierangroo.me
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
params:
  abbrDateFmt: "Jan 2"
  author: "Blog Author"
  brandIconFile: "images/brandIcon.svg"
  dateFmt: "2006-01-02"
#  customStylesheets: # Use to override theme styles, like logo size
#    - "css/custom.css"
  social:
    - name: GitHub
      url: https://github.com/kierangroome
    - name: Twitter
      url: https://twitter.com/kierangroome
    - name: Quizlet
      url: https://quizlet.com/ian-s-mcb
    - name: Reddit
      url: https://www.reddit.com/user/ian-s-mcb
    - name: StackOverflow
      url: https://stackoverflow.com/users/3417846/ian-s-mcb
  subtitle: "Macromedia Enthusiast"
